#+TITLE: Build.sh

* Introduction
This project provide a simple shell script for manipulate git branches automatically with Continuous Integrations.

You can release a version or publish docs on GitHub-pages just using commit message.

* How to use

1. Download source at [[https://raw.githubusercontent.com/mrlee23/Build.sh/master/build.sh]]
** example of .travis.yml
#+BEGIN_SRC yaml
before_script:
  - curl -o build.sh https://raw.githubusercontent.com/mrlee23/Build.sh/master/build.sh

after_success: if [ "$TRAVIS_BRANCH" == "master" ]; then bash build.sh release; fi
#+END_SRC

* Variables
- =GH_TOKEN= <Required> : GitHub token.
- =RELEASE_BRANCH= <Optional> : Release branch name. This branch will be checkout using orphan option.
- =RELEASE_DIR= <Optional> : Temporary directory to save exists repo data.
- =RELEASE_REGEXP= <Optional> : REGEXP for check that repo has a releasable commit.
- =RELEASE_VERSION_REGEXP= : REGEXP for detect version number.

* Commands

** Release
- Make release branch.
- Detecting released commit or not.
- Commit & Push a released commit only.
- After finished releasing sequences, will be checkout to branch selected before.
- After then, you can publish to package manager with =release= branch. (eg. npm publish)
